config/routes.rb
Rails.application.routes.draw do

  resources :agent, :controller => 'agent', :as => 'agents'

  resources :creator, :controller => 'creator', :as => 'creators'

  resources  :object_resource, :controller => 'object_resource', :as => 'object_resources'

  resources  :collection, :controller => 'collection', :as => 'collections'

  root to: redirect('object_resource/new')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/object_resource.rb
# frozen_string_literal: true
class ObjectResource < Valkyrie::Resource
  include Valkyrie::Resource::AccessControls
  attribute :title, Valkyrie::Types::Set
  attribute :date_created, Valkyrie::Types::Set
  attribute :creator_ids, Valkyrie::Types::Set
  attribute :member_of_collection_ids, Valkyrie::Types::Set
  attribute :member_ids, Valkyrie::Types::Array

  def primary_terms
    [:title, :date_created, :creator_ids, :member_of_collection_ids, :member_ids]
  end
end

app/controllers/object_resource_controller.rb
class ObjectResourceController < ApplicationController
  def resource_class
    ObjectResource
  end

  def metadata_adapter
    Valkyrie.config.metadata_adapter
  end

  def index
    @model = metadata_adapter.query_service.find_all
  end

  def show
    @model = metadata_adapter.query_service.find_by(id: Valkyrie::ID.new(params[:id]))
    @collections = metadata_adapter.query_service.find_all_of_model(model: Collection)
    @agents = metadata_adapter.query_service.find_all_of_model(model: Agent)
    @components = metadata_adapter.query_service.find_all_of_model(model: ObjectResource)
  end

  def new
    @collections = metadata_adapter.query_service.find_all_of_model(model: Collection).map { |rec| [rec.title.first, rec.id] }
    @agents = metadata_adapter.query_service.find_all_of_model(model: Agent).map { |rec| [rec.label.first, rec.id] }
    @components = metadata_adapter.query_service.find_all_of_model(model: ObjectResource).map { |rec| [rec.title.first, rec.id] }
    @model = ObjectResource.new
  end

  def edit
    @collections = metadata_adapter.query_service.find_all_of_model(model: Collection).map { |rec| [rec.title.first, rec.id] }
    @agents = metadata_adapter.query_service.find_all_of_model(model: Agent).map { |rec| [rec.label.first, rec.id] }
    @components = metadata_adapter.query_service.find_all_of_model(model: ObjectResource)
      .reject { |rec| rec.id.to_s == @model.id.to_s }
      .map { |rec| [rec.title.first, rec.id] }
    @model = metadata_adapter.query_service.find_by(id: Valkyrie::ID.new(params[:id]))
  end

  def create
    @model = ObjectResource.new(require_params.to_h)
    @model = metadata_adapter.persister.save(resource: @model);
    if @model
      redirect_to @model, notice: 'Work was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    @model = metadata_adapter.query_service.find_by(id: params[:id])
    require_params.to_h.map do |key, value|
      @model.send("#{key}=", value)
    end
    if metadata_adapter.persister.save(resource: @model)
      redirect_to @model, notice: 'Object was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @model = metadata_adapter.query_service.find_by(id: params[:id])

    metadata_adapter.persister.delete(resource: @model)
    flash[:alert] = "Deleted #{@model}"
    redirect_to object_resources_path
  end

  def _prefixes
    # This allows us to use the attributes templates in base, while prefering
    @_prefixes ||= super + ['base']
  end

  def require_params
    params.require(:object_resource)
          .permit(:title,
                  :date_created,
                  creator_ids: [],
                  member_of_collection_ids: [],
                  member_ids: [])
  end
end

app/views/object_resource/show.html.erb
<h1>Object#show</h1>
<div id="content">
  <table class="table table-striped agent attributes">
    <thead>
      <tr align="left"><th>Attribute name</th><th>Attribute values</th></tr>
    </thead>
    <tbody>
      <tr><td>Title: </td><td><%= @model.title.first %></td></tr>
      <% if @model.date_created.size() > 0 %>
        <tr><td>Date Created: </td><td><%= @model.date_created.first %></td></tr>
      <% end %>

      <% if @model.creator_ids.size() > 0 %>
        <tr><td valign="top">Publisher: </td><td>
          <% @model.creator_ids.each do |creator_id| %>
            <% @agents.each do |rec| %>
              <% if (rec.id.to_s == creator_id) %>
                <div><%= link_to rec.label.first, agent_path(rec.id) %></div>
              <% end %>
            <% end %>
          <% end %>
        </td></tr>
      <% end %>

      <% if @model.member_of_collection_ids.size() > 0 %>
        <tr><td valign="top">Collections: </td><td>
          <% @model.member_of_collection_ids.each do |member_id| %>
            <% @collections.each do |rec| %>
              <% if (rec.id.to_s == member_id) %>
                <div><%= link_to rec.title.first, collection_path(rec.id) %></div>
              <% end %>
            <% end %>
          <% end %>
        </td></tr>
      <% end %>

      <% if @model.member_ids.size() > 0 %>
        <tr><td valign="top">Components: </td><td>
          <% @model.member_ids.each do |member_id| %>
            <% @components.each do |rec| %>
              <% if (rec.id.to_s == member_id) %>
                <div><%= link_to rec.title.first, object_resource_path(rec.id) %></div>
              <% end %>
            <% end %>
          <% end %>
        </td></tr>
      <% end %>
    </tbody>
  </table>
  <button type="button" onclick="document.location='<%= edit_object_resource_path @model %>'">Edit</button>
</div>