config/routes.rb
Rails.application.routes.draw do

  resources :agent, :controller => 'agent', :as => 'agents'

  resources :creator, :controller => 'creator', :as => 'creators'

  resources  :object_resource, :controller => 'object_resource', :as => 'object_resources'

  resources  :collection, :controller => 'collection', :as => 'collections'

  root to: redirect('object_resource/new')
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/collection.rb
# frozen_string_literal: true
class Collection < Valkyrie::Resource
  include Valkyrie::Resource::AccessControls
  attribute :title, Valkyrie::Types::Set
  attribute :description, Valkyrie::Types::Set
  attribute :date_created, Valkyrie::Types::Set
  attribute :publisher_ids, Valkyrie::Types::Set
  attribute :member_collection_ids, Valkyrie::Types::Array

  def primary_terms
    [:title, :description, :date_created, :publisher_ids, :member_collection_ids]
  end
end

app/controllers/collection_controller.rb
class CollectionController < ApplicationController
  def metadata_adapter
    Valkyrie.config.metadata_adapter
  end

  def index
  end

  def show
    @model = metadata_adapter.query_service.find_by(id: params[:id])
    @collections = metadata_adapter.query_service.find_all_of_model(model: Collection)
    @agents = metadata_adapter.query_service.find_all_of_model(model: Agent)
  end

  def edit
    @model = metadata_adapter.query_service.find_by(id: params[:id])
    @collections = metadata_adapter.query_service.find_all_of_model(model: Collection)
      .reject { |rec| rec.id.to_s == @model.id.to_s }
      .map { |rec| [rec.title.first, rec.id] }
    @agents = metadata_adapter.query_service.find_all_of_model(model: Agent).map { |rec| [rec.label.first, rec.id] }
  end

  def new
    @collections = metadata_adapter.query_service.find_all_of_model(model: Collection).map { |rec| [rec.title.first, rec.id] }
    @agents = metadata_adapter.query_service.find_all_of_model(model: Agent).map { |rec| [rec.label.first, rec.id] }
    @model = Collection.new
  end

  def create
    @collection = Collection.new(require_params.to_h)
    @collection = metadata_adapter.persister.save(resource: @collection);
    if @collection
      redirect_to @collection, notice: 'Collection was successfully created.'
    else
      @collections = metadata_adapter.query_service.find_all_of_model(model: Collection)
      @agents = metadata_adapter.query_service.find_all_of_model(model: Agent)
      render action: 'new'
    end
  end

  def update
    @collection = metadata_adapter.query_service.find_by(id: params[:id])
    require_params.to_h.map do |key, value|
      @collection.send("#{key}=", value)
    end
    if metadata_adapter.persister.save(resource: @collection)
      redirect_to @collection, notice: 'Collection was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
  end

  def _prefixes
    # This allows us to use the attributes templates in base, while prefering
    @_prefixes ||= super + ['base']
  end

  def require_params
    params.require(:collection)
          .permit(:title,
                  :description,
                  :date_created,
                  publisher_ids: [],
                  member_collection_ids: [])
  end
end

app/views/collection/show.html.erb
<h1>Collection#show</h1>
<div id="content">
  <table class="table table-striped agent attributes">
    <thead>
      <tr align="left"><th>Attribute name</th><th>Attribute values</th></tr>
    </thead>
      <tr><td>Title: </td><td><%= @model.title.first %></td></tr>
      <% if @model.description.size() > 0 %>
        <tr><td>Description: </td><td><%= @model.description.first %></td></tr>
      <% end %>
      <% if @model.date_created.size() > 0 %>
        <tr><td>Date Created: </td><td><%= @model.date_created.first %></td></tr>
      <% end %>
      <% if @model.publisher_ids.size() > 0 %>
        <tr><td valign="top">Publisher: </td><td>
          <% @model.publisher_ids.each do |publisher_id| %>
            <% @agents.each do |rec| %>
              <% if (rec.id.to_s == publisher_id) %>
                <div><%= link_to rec.label.first, agent_path(rec.id) %></div>
              <% end %>
            <% end %>
          <% end %>
        </td></tr>
      <% end %>
      <% if @model.member_collection_ids.size() > 0 %>
        <tr><td valign="top">Child Collections: </td><td>
          <% @model.member_collection_ids.each do |member_id| %>
            <% @collections.each do |rec| %>
              <% if (rec.id.to_s == member_id) %>
                <div><%= link_to rec.title.first, collection_path(rec.id) %></div>
              <% end %>
            <% end %>
          <% end %>
        </td></tr>
      <% end %>
    </tbody>
  </table>
  <button type="button" onclick="document.location='<%= edit_collection_path @model %>'">Edit</button>
</div>